services:
  - type: web
    name: smart-task-ai
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: frankfurt
    envVars:
      - key: PORT
        value: 8000
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: WEB_APP_URL
        sync: false
